version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/blogprojectdrf
permissions:
  - object: /home/ubuntu/blogprojectdrf
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: deployment-archive/scripts/clean_instance.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment-archive/scripts/instance_os_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: deployment-archive/scripts/python_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: deployment-archive/scripts/gunicorn.sh
      timeout: 300
      runas: ubuntu
    - location: deployment-archive/scripts/nginx.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deployment-archive/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: deployment-archive/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
