version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/blogprojectdrf
permissions:
  - object: /home/ubuntu/blogprojectdrf
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/instance_os_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/python_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/gunicorn.sh
      timeout: 300
      runas: root
    - location: scripts/nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
