version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify the Python version
    commands:
      - echo Installing system dependencies...
      - sudo apt-get update
      - sudo apt-get install -y python3-pip python3-venv

  pre_build:
    commands:
      - echo Setting up the environment...
      - python3 -m venv env
      - source env/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:    
      - echo Building the application
     

  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  files:
    - '**/*'
